name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'bench/**'
      - 'examples/**'
      - 'shots/**'
    branches:
    - master
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'bench/**'
      - 'examples/**'
      - 'shots/**'
    branches:
    - master

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    strategy:
      matrix:
        nodejs: [8, 10, 12, 14, 16]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install
      run: |
        npm install
        npm install -g nyc@13

    - name: Test w/ Coverage
      run: nyc --include=src npm test

    - name: Report
      if: matrix.nodejs >= 16 && matrix.os == 'ubuntu-latest'
      run: |
        nyc report --reporter=text-lcov > coverage.lcov
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
